# Generated by Django 2.1.5 on 2019-01-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.CharField(max_length=200),
        ),
    ]
